SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

DROP TABLE IF EXISTS `PoljaData`;

CREATE TABLE `PoljaData` (
    `id` INT(11) NOT NULL,
    `polje` VARCHAR(3) NOT NULL,
    `knjiga` INT(11) NOT NULL,
    `podpolja` VARCHAR(5000) NOT NULL,
    `indikator` VARCHAR(2) NOT NULL
)  ENGINE=INNODB DEFAULT CHARSET=utf8;


ALTER TABLE `PoljaData`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `PoljaData`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=0;